### ISSUE TITLE
Thoughts on using a ".override" file...

### ISSUE THREAD

**Issue by howardroark** [AbhishekGhosh/Nginx-PHP5-FPM-Restart-Fix-on-Ubuntu#4]
Hey,

On the Ubuntu launchpad forums it is suggested that people create an `/etc/init/php5-fpm.override` file with just `reload signal USR2` in it.  Just wondering if you saw any pitfalls in that method vs editing `/etc/init/php5-fpm.conf` to uncomment that line?

https://bugs.launchpad.net/ubuntu/+source/php5/+bug/1242376/comments/16
https://bugs.launchpad.net/ubuntu/+source/php5/+bug/1242376/comments/17

**Comment by AbhishekGhosh** [comment]
No, there is no pitfall to create an `/etc/init/php5-fpm.override` file. The reason of fixing in this way was pretty simple, I was not aware of the comment at that time when this fix was written. Users can use any method of his/her convenience, in my opinion.

**Comment by howardroark** [comment]
Yup, that is what I figured :) Thanks!
